### ISSUE TITLE
Android: tel: protocol seen as net: protocol?

### ISSUE THREAD

**Issue by Bibi56** [caresteouvert/caresteouvert_android#1]
**Describe the bug**
Fdroid version : net::ERR_UNKOWN_URL_SCHEME

**To Reproduce**
1. Use the app
2. Go to  https://www.caresteouvert.fr/@47.824165,-3.489516,15.31/place/n5167185587 (probably any place with a phone number)
3. Click on the phone line
4. See error: net::ERR_UNKNOWN_SCHEME

**Expected behavior**
Same as on Firefox on the same mobile: call the number with a phone app, add as contact...

**Smartphone (please complete the following information):**
 - Device: honor 5C NEM-L151
 - OS: 7.0

**Comment by PanierAvide** [comment]
Seems quite weird as link is well formated. Is this issue also happening if you browse the website through web browser on your mobile ?

**Comment by Bibi56** [comment]
No, on the mobile, Firefox works fine. That's why the expected behavior was 

> 

> Same as on Firefox on the same mobile

I tried on another phone number, same behavior. Firefox propose to use a phone app with the intent:
+33%20....#Internt;;scheme=tel;launchFlags=0x3000000;launchHWFlags=0x400;S.comandroid.browser.application_id=org.mozilla.firefox;end

**Comment by ericafenyo** [comment]
I was able to reproduce this by either clicking on a telephone number or an email address. 

**Screenshot Samsung S10**

![IMAGE 2020-04-18 18:50:33](https://user-images.githubusercontent.com/32494423/79643887-8f2e8900-81a5-11ea-9f91-dfff96cff837.jpg)

**Comment by ericafenyo** [comment]
Web view couldn't parse the `tel:` and `mailto:` protocols, so we have to delegate these intents to the android system to handle.

I would also suggest opening links such us https://wiki.openstreetmap.org/wiki/France/Covid-19 in an external browser since it is not directly related to the functionality of the app.
